// Copyright (C) 2012 Pedro Lamarão <pedro.lamarao@gmail.com>. All rights reserved.

.att_syntax

//

.global __division_by_zero_start
.type   __division_by_zero_start, STT_FUNC
.func   __division_by_zero_start

__division_by_zero_start:
	iret

.endfunc

//

.global __debug_start
.type   __debug_start, STT_FUNC
.func   __debug_start

__debug_start:
	iret

.endfunc

//

.global __nmi_start
.type   __nmi_start, STT_FUNC
.func   __nmi_start

__nmi_start:
	iret

.endfunc

//

.global __breakpoint_start
.type   __breakpoint_start, STT_FUNC
.func   __breakpoint_start

__breakpoint_start:
	iret

.endfunc

//

.global __overflow_start
.type   __overflow_start, STT_FUNC
.func   __overflow_start

__overflow_start:
	iret

.endfunc

//

.global __bound_range_exceeded_start
.type   __bound_range_exceeded_start, STT_FUNC
.func   __bound_range_exceeded_start

__bound_range_exceeded_start:
	iret

.endfunc

//

.global __invalid_opcode_start
.type   __invalid_opcode_start, STT_FUNC
.func   __invalid_opcode_start

__invalid_opcode_start:
	iret

.endfunc

//

.global __device_not_available_start
.type   __device_not_available_start, STT_FUNC
.func   __device_not_available_start

__device_not_available_start:
	iret

.endfunc

//

.global __double_fault_start
.type   __double_fault_start, STT_FUNC
.func   __double_fault_start

__double_fault_start:
	iret

.endfunc

//

.global __invalid_tss_start
.type   __invalid_tss_start, STT_FUNC
.func   __invalid_tss_start

__invalid_tss_start:
	iret

.endfunc

//

.global __segment_not_present_start
.type   __segment_not_present_start, STT_FUNC
.func   __segment_not_present_start

__segment_not_present_start:
	iret

.endfunc

//

.global __stack_fault_start
.type   __stack_fault_start, STT_FUNC
.func   __stack_fault_start

__stack_fault_start:
	iret

.endfunc

//

.global __general_protection_fault_start
.type   __general_protection_fault_start, STT_FUNC
.func   __general_protection_fault_start

__general_protection_fault_start:
	iret

.endfunc

//

.global __page_fault_start
.type   __page_fault_start, STT_FUNC
.func   __page_fault_start

__page_fault_start:
	iret

.endfunc

//

.global __fpu_error_start
.type   __fpu_error_start, STT_FUNC
.func   __fpu_error_start

__fpu_error_start:
	iret

.endfunc

//

.global __alignment_fault_start
.type   __alignment_fault_start, STT_FUNC
.func   __alignment_fault_start

__alignment_fault_start:
	iret

.endfunc

//

.global __machine_fault_start
.type   __machine_fault_start, STT_FUNC
.func   __machine_fault_start

__machine_fault_start:
	iret

.endfunc

//

.global __simd_fault_start
.type   __simd_fault_start, STT_FUNC
.func   __simd_fault_start

__simd_fault_start:
	iret

.endfunc

//

.global __user_interrupt_start
.type   __user_interrupt_start, STT_FUNC
.func   __user_interrupt_start

__user_interrupt_start:
	iret

.endfunc

//

.global __irq1_start
.type   __irq1_start, STT_FUNC
.func   __irq1_start

__irq1_start:
	iret

.endfunc

//

.global __irq2_start
.type   __irq2_start, STT_FUNC
.func   __irq2_start

__irq2_start:
	iret

.endfunc

//

.global __irq3_start
.type   __irq3_start, STT_FUNC
.func   __irq3_start

__irq3_start:
	iret

.endfunc

//

.global __irq4_start
.type   __irq4_start, STT_FUNC
.func   __irq4_start

__irq4_start:
	iret

.endfunc

//

.global __irq5_start
.type   __irq5_start, STT_FUNC
.func   __irq5_start

__irq5_start:
	iret

.endfunc

//

.global __irq6_start
.type   __irq6_start, STT_FUNC
.func   __irq6_start

__irq6_start:
	iret

.endfunc

//

.global __irq7_start
.type   __irq7_start, STT_FUNC
.func   __irq7_start

__irq7_start:
	iret

.endfunc

//

.global __irq8_start
.type   __irq8_start, STT_FUNC
.func   __irq8_start

__irq8_start:
	iret

.endfunc

//

.global __irq9_start
.type   __irq9_start, STT_FUNC
.func   __irq9_start

__irq9_start:
	iret

.endfunc

//

.global __irq10_start
.type   __irq10_start, STT_FUNC
.func   __irq10_start

__irq10_start:
	iret

.endfunc

//

.global __irq11_start
.type   __irq11_start, STT_FUNC
.func   __irq11_start

__irq11_start:
	iret

.endfunc

//

.global __irq12_start
.type   __irq12_start, STT_FUNC
.func   __irq12_start

__irq12_start:
	iret

.endfunc

//

.global __irq13_start
.type   __irq13_start, STT_FUNC
.func   __irq13_start

__irq13_start:
	iret

.endfunc

//

.global __irq14_start
.type   __irq14_start, STT_FUNC
.func   __irq14_start

__irq14_start:
	iret

.endfunc

//

.global __irq15_start
.type   __irq15_start, STT_FUNC
.func   __irq15_start

__irq15_start:
	iret

.endfunc

