This project's purpose is to achieve "high engineering" for the "bare metal".
When something goes wrong, the "bare metal" explains very little, and abstractions become a burden.

At debug time, one must inspect the lowest level.
There is no need to abandon high level abstractions for this purpose.
The `objdump` tool allows one to inspect the lowest level definitions generated by the tools.
The LLVM toolset provides a `llvm-objdump` equivalent.

Let us inspect the program image for the `main` system test of the `x86` library.

The `x86_32-elf-multiboot` target is expected to generate and ELF32 image for the `i386` architecture.

To discover what kind of image we actually have, use the `-a` or `--archive-headers` option.

[source,powershell]
----
> llvm-objdump .\x86\test\x86_32-elf-multiboot2\main\build\exes\main\-x86_32-elf-multiboot2\main -a

.\x86\test\x86_32-elf-multiboot2\main\build\exes\main\-x86_32-elf-multiboot2\main:      file format elf32-i386
----

Note how the image has the expected format.

The `x86_32-elf-multiboot` target is expected to position `.multiboot2.*` sections at the start of the image.
Multiboot2 requires the "request header" to be positioned in the initial 32 KiB of the image.

To discover what is the image's actual layout, use the `-h` or `--section-headers` option.

[source,powershell]
----
> llvm-objdump .\x86\test\x86_32-elf-multiboot2\main\build\exes\main\-x86_32-elf-multiboot2\main -h

PS C:\Users\Pedro\Code\psys> llvm-objdump .\x86\test\x86_32-elf-multiboot2\main\build\exes\main\-x86_32-elf-multiboot2\main -h

Sections:
Idx Name                Size     VMA      Type
  0                     00000000 00000000
  1 .eh_frame_hdr       00000034 00001000 DATA
  2 .eh_frame           000000b0 00001034 DATA
  3 .multiboot2.start   00000015 000010f0 TEXT
  4 .multiboot2.request 00000018 00001108 DATA
  5 .multiboot2.stack   00004000 00001120 DATA
  6 .text               00000065 00005120 TEXT
  7 .data               00000008 00005188 BSS
  8 .debug_abbrev       0000017d 00000000 DEBUG
  9 .debug_info         00000308 00000000 DEBUG
 10 .debug_ranges       00000018 00000000 DEBUG
 11 .debug_str          000004a8 00000000 DEBUG
 12 .comment            00000029 00000000
 13 .debug_line         00000317 00000000 DEBUG
 14 .symtab             000000b0 00000000
 15 .shstrtab           000000bf 00000000
 16 .strtab             000000cd 00000000
PS C:\Users\Pedro\Code\psys>
----

Note how we do not place the `.multiboot2.*` sections at the very start of the image in this case!

The `x86_32-elf-multiboot2` target is expected to set the image's entry point to `multiboot2_start`.

To discover the address of the actual entry point, use the `-f` or `--file-headers` option.

[source,powershell]
----
PS C:\Users\Pedro\Code\psys> llvm-objdump .\x86\test\x86_32-elf-multiboot2\main\build\exes\main\-x86_32-elf-multiboot2\main -f

.\x86\test\x86_32-elf-multiboot2\main\build\exes\main\-x86_32-elf-multiboot2\main:      file format elf32-i386
architecture: i386
start address: 0x000010f0
----

To discover which symbol corresponds, we must inspect the symbol table with `-t` or `--syms`.

[source,powershell]
----
PS C:\Users\Pedro\Code\psys> llvm-objdump .\x86\test\x86_32-elf-multiboot2\main\build\exes\main\-x86_32-elf-multiboot2\main -t

.\x86\test\x86_32-elf-multiboot2\main\build\exes\main\-x86_32-elf-multiboot2\main:      file format elf32-i386

SYMBOL TABLE:
00000000 l    df *ABS*  00000000 ld-temp.o
00005120 l     F .text  00000019 _ZN4psys4mainEv
00001120 l     O .multiboot2.stack      00004000 _ZN10multiboot25stackE
00005160 l     F .text  00000025 _ZN10multiboot24mainEU7_ExtIntILi32EEjRNS_16information_listE
00005188 g     O .data  00000004 _test_control
000010f0 g     F .multiboot2.start      00000015 multiboot2_start
00001108 g     O .multiboot2.request    00000018 _ZN10multiboot27requestE
00005140 g     F .text  00000005 _test_start
00005150 g     F .text  00000005 _test_finish
0000518c g     O .data  00000004 _test_debug
----

Note how the start address `0x000010f0` matches the symbol `multiboot2_start` in section `.multiboot2.start`.

The `multiboot2_start` procedure provided by the `multiboot2:start` library
is supposed to prepare the execution environment then call a C++ procedure named `multiboot2::main`.

To discover what the actual code is doing, use the `-d` or `--disassemble` option.
To select a specific section to disassemble, use the `-j` or `--section-name` option.
For `x86` targets, the default syntax is AT&T.
To output Intel syntax, use the `--x86-asm-syntax=intel` option.
To demangle C++ names, use the `-C` or `--demangle` option.

[source,powershell]
----
PS C:\Users\Pedro\Code\psys> llvm-objdump .\x86\test\x86_32-elf-multiboot2\main\build\exes\main\-x86_32-elf-multiboot2\main -d -j '.multiboot2.start' --x86-asm-syntax=intel -C

.\x86\test\x86_32-elf-multiboot2\main\build\exes\main\-x86_32-elf-multiboot2\main:      file format elf32-i386

Disassembly of section .multiboot2.start:

000010f0 <multiboot2_start>:
    10f0: bc 20 51 00 00                mov     esp, 20768
    10f5: 31 c9                         xor     ecx, ecx
    10f7: 51                            push    ecx
    10f8: 66 9d                         popf
    10fa: 53                            push    ebx
    10fb: 50                            push    eax
    10fc: e8 5f 40 00 00                call    0x5160 <multiboot2::main(unsigned int _ExtInt<32>, multiboot2::information_list&)>
    1101: fa                            cli
    1102: f4                            hlt
    1103: eb fd                         jmp     0x1102 <multiboot2_start+0x12>
----