name: "ubuntu"
on: [pull_request]
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Validate Gradle Wrapper"
        uses: gradle/wrapper-validation-action@v1
      - name: "Set up JDK 11"
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "temurin"
      - name: Cache LLVM 13
        id: cache-llvm
        uses: actions/cache@v2
        with:
          key: llvm-13
          path: |
            C:/Program Files/LLVM
            ./llvm
      - name: "Install LLVM 13"
        uses: KyleMayes/install-llvm-action@v1.5.1
        with:
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
          ubuntu-version: 18.04
          version: 13
      - name: "Build with Gradle"
        uses: gradle/gradle-build-action@v2.1.3
        with:
          arguments: build
