name: "ubuntu"
on: [pull_request,workflow_dispatch]
jobs:
  build-llvm-13:
    name: "build with llvm 13"
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Validate Gradle Wrapper"
        uses: gradle/wrapper-validation-action@v1
      - name: "Set up JDK 17"
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"
      - name: "Install LLVM 13"
        uses: KyleMayes/install-llvm-action@v1.5.2
        with:
          ubuntu-version: 18.04
          version: 13
      - name: "Build with Gradle"
        uses: gradle/gradle-build-action@v2.1.6
        with:
          arguments: build
  build-llvm-14:
    name: "build with llvm 14"
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Validate Gradle Wrapper"
        uses: gradle/wrapper-validation-action@v1
      - name: "Set up JDK 17"
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"
      - name: "Install LLVM 14"
        uses: KyleMayes/install-llvm-action@v1.5.2
        with:
          ubuntu-version: 18.04
          version: 14
      - name: "Build with Gradle"
        uses: gradle/gradle-build-action@v2.1.6
        with:
          arguments: build
