name: "ubuntu"
on: [pull_request,workflow_dispatch]
jobs:
  llvm-16-target-host:
    name: "build with LLVM 16 target host"
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Validate Gradle Wrapper"
        uses: gradle/wrapper-validation-action@v1
      - name: "Set up JDK 17"
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - name: "Install LLVM 16"
        uses: KyleMayes/install-llvm-action@v1
        with:
          ubuntu-version: 22.04
          version: 16.0.4
      - name: "Install Ninja"
        uses: seanmiddleditch/gha-setup-ninja@v3
      - name: "Invoke Gradle"
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --info --no-daemon build
  llvm-17-target-host:
    name: "build with LLVM 17 target host"
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Validate Gradle Wrapper"
        uses: gradle/wrapper-validation-action@v1
      - name: "Set up JDK 17"
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - name: "Install LLVM 17"
        uses: KyleMayes/install-llvm-action@v1
        with:
          force-version: true
          ubuntu-version: 22.04
          version: 17.0.2
      - name: "Install Ninja"
        uses: seanmiddleditch/gha-setup-ninja@v3
      - name: "Invoke Gradle"
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --info --no-daemon build
  llvm-16-target-i686-elf:
    name: "assemble with LLVM 16 target i686-elf"
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Validate Gradle Wrapper"
        uses: gradle/wrapper-validation-action@v1
      - name: "Set up JDK 17"
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - name: "Install LLVM 16"
        uses: KyleMayes/install-llvm-action@v1
        with:
          ubuntu-version: 22.04
          version: 16.0.4
      - name: "Invoke Gradle"
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --info --no-daemon image "-Pmetal.target=i686-elf"
  llvm-17-target-i686-elf:
    name: "assemble with LLVM 17 target i686-elf"
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Validate Gradle Wrapper"
        uses: gradle/wrapper-validation-action@v1
      - name: "Set up JDK 17"
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - name: "Install LLVM 16"
        uses: KyleMayes/install-llvm-action@v1
        with:
          force-version: true
          ubuntu-version: 22.04
          version: 17.0.2
      - name: "Invoke Gradle"
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --info --no-daemon image "-Pmetal.target=i686-elf"