name: "windows-latest"
on: [pull_request]
jobs:
  build:
    name: "Build"
    runs-on: windows-latest
    env:
      JAVA_HOME: $JAVA_HOME_11_X64
    timeout-minutes: 10
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Validate Gradle Wrapper"
        uses: gradle/wrapper-validation-action@v1
      - name: "Build with Gradle"
        uses: gradle/gradle-build-action@v2.1.3
        with:
          arguments: build
